var question = [
"1.Given the choice of anyone in the world, whom would you want as a dinner guest?",
"隨便選一個人，妳會選擇誰一起晚餐？",
"2.Would you like to be famous? In what way?",
"妳想要變有名嗎？以什麼方式？",
"3.Before making a telephone call, do you ever rehearse what you are going to say? Why?",
"通話之前，妳有曾經練習過要說什麼嗎？為什麼？",
"4.What would constitute a “perfect” day for you?",
"妳的完美的一天是什麼樣子的？",
"5.When did you last sing to yourself? To someone else?",
"妳最後一次唱歌給自己聽是什麼時候？那唱給別人聽呢？",
"6.If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?",
"如果妳可以活到90歲，可以保留妳的身體或心靈為30歲時的狀態60年，妳會保留哪一個？",
"7.Do you have a secret hunch about how you will die?",
"妳有妳將會怎麼死的直覺嗎？",
"8.Name three things you and your partner appear to have in common.",
"講出三件妳跟妳的對象有共同點的地方",
"9.For what in your life do you feel most grateful?",
"妳生命中最覺得感激的事？",
"10.If you could change anything about the way you were raised, what would it be?",
"如果妳可以改變妳成長的方式，妳想改變什麼？",
"11.Take four minutes and tell your partner your life story in as much detail as possible.",
"花四分鐘盡量細節地告訴妳的妳的生命故事",
"12.If you could wake up tomorrow having gained any one quality or ability, what would it be?",
"如果妳明天醒來可以擁有一種特質或能力，那會是什麼？",
"13.If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?",
"如果有一顆水晶球可以告訴妳關於妳自己、妳的人生、妳的未來或任何的事情，妳想知道什麼？",
"14.Is there something that you’ve dreamed of doing for a long time? Why haven’t you done it?",
"有任何妳長久以來都想做的事情嗎？為什麼妳還沒做？",
"15.What is the greatest accomplishment of your life?",
"妳一生最大的成就是什麼？",
"16.What do you value most in a friendship?",
"友誼中妳最重視什麼？",
"17.What is your most treasured memory?",
"什麼是妳最珍貴的回憶？",
"18.What is your most terrible memory?",
"什麼是妳最糟糕的回憶",
"19.If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?",
"如果妳知道某一年妳會突然死掉，妳會改變妳現在的生活方式嗎？為什麼？",
"20.What does friendship mean to you?",
"友誼對妳來說意味著什麼？",
"21.What roles do love and affection play in your life?",
"愛情跟感情在妳的生活中扮演什麼角色",
"22.Alternate sharing something you consider a positive characteristic of your partner. Share a total of five items.",
"交替分享妳的正面特質。分享五項。",
"23.How close and warm is your family? Do you feel your childhood was happier than most other people’s?",
"妳的家庭關係多溫暖跟緊密？妳覺得妳的孩童時代比起其他人要快樂嗎？",
"24.How do you feel about your relationship with your mother?",
"妳覺得妳跟妳媽媽的關係如何？",
"25.Make three true “we” statements each. For instance, “We are both in this room feeling … “",
"兩人分別造三個我們開頭的句子，舉例：我們在這房裡都覺得....",
"26.Complete this sentence: “I wish I had someone with whom I could share … “",
"完成該句子，'我希望我可以有人分享.....'",
"27.If you were going to become a close friend with your partner, please share what would be important for him or her to know.",
"如果妳將跟妳的對象變成關係緊密的朋友，請分享一些妳認為重要的是讓他知道",
"28.Tell your partner what you like about them; be very honest this time, saying things that you might not say to someone you’ve just met.",
"告訴妳的夥伴妳喜歡他們什麼; 這次要很誠實，說一些初次見面妳可能不會對對方說的話",
"29.Share with your partner an embarrassing moment in your life.",
"分享給妳的夥伴，妳生命中一次尷尬出糗的經驗",
"30.When did you last cry in front of another person? By yourself?",
"妳最後一次在人前哭是什麼時候？那麼獨自哭又是什麼時候？",
"31.Tell your partner something that you like about them already.",
"告訴妳的夥伴一些妳已經喜歡他們的事情",
"32.What, if anything, is too serious to be joked about?",
"若有，哪些是不太能開玩笑的事？",
"33.If you were to die this evening with no opportunity to communicate with anyone, what would you most regret not having told someone? Why haven’t you told them yet?",
"如果妳今晚就要死掉了且沒有機會跟任何人說，妳最後悔沒告訴人的事情是什麼？為什麼妳不告訴她們？",
"34.Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?",
"妳的家，所有妳擁有的東西，找火了。在妳救了妳愛的人跟寵物之後，妳有時間可以安全地救下最後一樣東西，那會是什麼？為什麼？",
"35.Of all the people in your family, whose death would you find most disturbing? Why?",
"妳家庭所有人中，誰的死亡可能讓妳最不安，為什麼？",
"36.Share a personal problem and ask your partner’s advice on how he or she might handle it. Also, ask your partner to reflect back to you how you seem to be feeling about the problem you have chosen.",
"分享一個妳自己的私人問題，並詢問妳的夥伴建議他們會怎麼處理這個問題。另外，請妳的夥伴向妳反映妳對所選擇問題的感覺"];












